ALL RECORDS:C47([CUSTOMER:2])
ORDER BY:C49([CUSTOMER:2]; [CUSTOMER:2]Lastname:2; >)
CREATE EMPTY SET:C140([CUSTOMER:2]; "$customersSet")
ADD TO SET:C119([CUSTOMER:2]; "$customersSet")

BuildInvoices

FORM GOTO PAGE:C247(3)